apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: acct_id.dkr.ecr.us-us-east-2.amazonaws.com/your_ecr_repo:latest'
        ports:
        - containerPort: 80
